/**
 * Mock data for quote component tests
 * @module __tests__/unit/components/quotes/mock-data
 */

import type { Quote } from '@/components/quotes/types';

export const mockQuote1: Quote = {
  id: 'quote-1',
  operator: {
    id: 'op-1',
    name: 'Elite Airways',
    logo: 'https://example.com/logo1.png',
    rating: 4.8,
    totalFlights: 1250,
    certifications: ['ARGUS Gold', 'Wyvern Wingman'],
    location: 'New York, NY',
  },
  aircraft: {
    id: 'ac-1',
    type: 'Light Jet',
    model: 'Citation CJ3',
    year: 2020,
    capacity: 7,
    range: 2040,
    speed: 480,
    amenities: ['WiFi', 'Refreshments', 'Entertainment System'],
    imageUrl: 'https://example.com/aircraft1.png',
  },
  pricing: {
    basePrice: 25000,
    taxes: 2500,
    fees: 500,
    total: 28000,
    currency: 'USD',
    pricePerHour: 3500,
    fuelSurcharge: 1000,
  },
  scores: {
    overall: 92,
    price: 85,
    safety: 95,
    availability: 90,
    operatorRating: 96,
    aircraftQuality: 88,
    breakdown: [
      {
        category: 'Safety',
        score: 95,
        maxScore: 100,
        weight: 0.3,
        description: 'Excellent safety record',
      },
      {
        category: 'Price',
        score: 85,
        maxScore: 100,
        weight: 0.25,
        description: 'Competitive pricing',
      },
      {
        category: 'Quality',
        score: 88,
        maxScore: 100,
        weight: 0.25,
        description: 'High quality aircraft',
      },
      {
        category: 'Availability',
        score: 90,
        maxScore: 100,
        weight: 0.2,
        description: 'Good availability',
      },
    ],
  },
  departureTime: '2025-12-15T10:00:00Z',
  arrivalTime: '2025-12-15T14:30:00Z',
  flightDuration: 270,
  features: ['WiFi', 'Catering', 'Ground Transportation', 'Priority Boarding'],
  prosCons: {
    pros: [
      'Excellent safety record with top certifications',
      'Modern aircraft with premium amenities',
      'Highly rated operator with extensive experience',
    ],
    cons: ['Slightly higher price point', 'Limited availability on weekends'],
  },
  rank: 1,
  recommended: true,
  notes: 'Best overall value with excellent safety record',
  createdAt: '2025-12-13T10:00:00Z',
  updatedAt: '2025-12-13T10:00:00Z',
};

export const mockQuote2: Quote = {
  id: 'quote-2',
  operator: {
    id: 'op-2',
    name: 'Sky Charter',
    logo: 'https://example.com/logo2.png',
    rating: 4.5,
    totalFlights: 980,
    certifications: ['ARGUS Platinum'],
    location: 'Los Angeles, CA',
  },
  aircraft: {
    id: 'ac-2',
    type: 'Light Jet',
    model: 'Phenom 300',
    year: 2019,
    capacity: 8,
    range: 2010,
    speed: 450,
    amenities: ['WiFi', 'Refreshments'],
    imageUrl: 'https://example.com/aircraft2.png',
  },
  pricing: {
    basePrice: 22000,
    taxes: 2200,
    fees: 800,
    total: 25000,
    currency: 'USD',
    pricePerHour: 3000,
  },
  scores: {
    overall: 88,
    price: 92,
    safety: 90,
    availability: 85,
    operatorRating: 90,
    aircraftQuality: 82,
    breakdown: [
      {
        category: 'Safety',
        score: 90,
        maxScore: 100,
        weight: 0.3,
        description: 'Good safety record',
      },
      {
        category: 'Price',
        score: 92,
        maxScore: 100,
        weight: 0.25,
        description: 'Best price',
      },
      {
        category: 'Quality',
        score: 82,
        maxScore: 100,
        weight: 0.25,
        description: 'Good quality aircraft',
      },
      {
        category: 'Availability',
        score: 85,
        maxScore: 100,
        weight: 0.2,
        description: 'Decent availability',
      },
    ],
  },
  departureTime: '2025-12-15T09:30:00Z',
  arrivalTime: '2025-12-15T14:00:00Z',
  flightDuration: 270,
  features: ['WiFi', 'Catering', 'Priority Boarding'],
  prosCons: {
    pros: ['Best price among comparable options', 'Good operator rating', 'Flexible scheduling'],
    cons: ['Older aircraft model', 'Fewer amenities than competitors'],
  },
  rank: 2,
  recommended: false,
  createdAt: '2025-12-13T10:00:00Z',
  updatedAt: '2025-12-13T10:00:00Z',
};

export const mockQuote3: Quote = {
  id: 'quote-3',
  operator: {
    id: 'op-3',
    name: 'Premium Jets',
    logo: 'https://example.com/logo3.png',
    rating: 4.9,
    totalFlights: 1500,
    certifications: ['ARGUS Platinum', 'IS-BAO Stage 3'],
    location: 'Miami, FL',
  },
  aircraft: {
    id: 'ac-3',
    type: 'Midsize Jet',
    model: 'Hawker 800XP',
    year: 2021,
    capacity: 9,
    range: 2540,
    speed: 500,
    amenities: ['WiFi', 'Full Galley', 'Entertainment System', 'Lavatory'],
    imageUrl: 'https://example.com/aircraft3.png',
  },
  pricing: {
    basePrice: 32000,
    taxes: 3200,
    fees: 800,
    total: 36000,
    currency: 'USD',
    pricePerHour: 4500,
    fuelSurcharge: 1500,
  },
  scores: {
    overall: 90,
    price: 75,
    safety: 98,
    availability: 88,
    operatorRating: 98,
    aircraftQuality: 95,
    breakdown: [
      {
        category: 'Safety',
        score: 98,
        maxScore: 100,
        weight: 0.3,
        description: 'Outstanding safety record',
      },
      {
        category: 'Price',
        score: 75,
        maxScore: 100,
        weight: 0.25,
        description: 'Premium pricing',
      },
      {
        category: 'Quality',
        score: 95,
        maxScore: 100,
        weight: 0.25,
        description: 'Exceptional quality',
      },
      {
        category: 'Availability',
        score: 88,
        maxScore: 100,
        weight: 0.2,
        description: 'Very good availability',
      },
    ],
  },
  departureTime: '2025-12-15T11:00:00Z',
  arrivalTime: '2025-12-15T15:15:00Z',
  flightDuration: 255,
  features: [
    'WiFi',
    'Full Catering',
    'Ground Transportation',
    'Priority Boarding',
    'Concierge Service',
  ],
  prosCons: {
    pros: [
      'Highest safety rating with multiple certifications',
      'Premium aircraft with luxury amenities',
      'Top-rated operator',
      'Fastest flight time',
    ],
    cons: ['Highest price point', 'May be overkill for short trips'],
  },
  rank: 3,
  recommended: false,
  createdAt: '2025-12-13T10:00:00Z',
  updatedAt: '2025-12-13T10:00:00Z',
};

export const mockQuotes: Quote[] = [mockQuote1, mockQuote2, mockQuote3];
