/**
 * Contract Types
 *
 * TypeScript types for the contract service layer.
 * Used for flight charter service agreements.
 *
 * @see lib/services/contract-service.ts
 * @see supabase/migrations/040_contracts_table.sql
 */

import type { Database } from './database';

// =============================================================================
// DATABASE TYPES (derived from Database schema)
// =============================================================================

/** Full contract row from database */
export type Contract = Database['public']['Tables']['contracts']['Row'];

/** Insert type for creating contracts */
export type ContractInsert = Database['public']['Tables']['contracts']['Insert'];

/** Update type for modifying contracts */
export type ContractUpdate = Database['public']['Tables']['contracts']['Update'];

/** Contract status enum */
export type ContractStatus =
  | 'draft'
  | 'sent'
  | 'viewed'
  | 'signed'
  | 'payment_pending'
  | 'paid'
  | 'completed'
  | 'cancelled'
  | 'expired';

// =============================================================================
// FLIGHT DETAILS TYPES
// =============================================================================

/**
 * Airport information for contract display
 */
export interface ContractAirport {
  /** ICAO code (e.g., "KTEB") */
  icao: string;
  /** Airport name (e.g., "Teterboro Airport") */
  name?: string;
  /** City name (e.g., "Teterboro") */
  city?: string;
}

/**
 * Flight details for contract generation
 * Captures all relevant flight information at contract time
 */
export interface ContractFlightDetails {
  /** Departure airport */
  departureAirport: ContractAirport;
  /** Arrival airport */
  arrivalAirport: ContractAirport;
  /** Departure date (YYYY-MM-DD) */
  departureDate: string;
  /** Departure time (HH:MM) - optional */
  departureTime?: string;
  /** Return date (YYYY-MM-DD) - optional for one-way */
  returnDate?: string;
  /** Aircraft type/category (e.g., "Turbo prop") */
  aircraftType: string;
  /** Aircraft model (e.g., "Pilatus PC 12") */
  aircraftModel?: string;
  /** Aircraft tail/registration number */
  tailNumber?: string;
  /** Number of passengers */
  passengers: number;
  /** Flight duration (e.g., "0:54") */
  flightDuration?: string;
  /** Distance in nautical miles */
  distanceNm?: number;
}

// =============================================================================
// PRICING TYPES
// =============================================================================

/**
 * Pricing breakdown for contract
 * Based on the example contract pricing structure
 */
export interface ContractPricing {
  /** Base flight cost */
  flightCost: number;
  /** Federal Excise Tax (typically 7.5% for US domestic) */
  federalExciseTax: number;
  /** Domestic segment fee (per passenger per segment, e.g., $5.20) */
  domesticSegmentFee: number;
  /** Subtotal before credit card fee */
  subtotal: number;
  /** Credit card processing fee percentage (default 5%) */
  creditCardFeePercentage: number;
  /** Total contract amount */
  totalAmount: number;
  /** Currency code (ISO 4217, e.g., "USD") */
  currency: string;
}

// =============================================================================
// CUSTOMER TYPES
// =============================================================================

/**
 * Customer information for contract
 */
export interface ContractCustomer {
  /** Customer's full name */
  name: string;
  /** Customer's email address */
  email: string;
  /** Company name (optional) */
  company?: string;
  /** Phone number (optional) */
  phone?: string;
}

// =============================================================================
// AMENITIES TYPES
// =============================================================================

/**
 * Aircraft amenities for contract display
 */
export interface ContractAmenities {
  /** Pets allowed */
  pets?: boolean;
  /** Smoking allowed */
  smoking?: boolean;
  /** In-flight WiFi available */
  wifi?: boolean;
  /** Full galley/catering */
  galley?: boolean;
  /** Enclosed lavatory */
  lavatory?: boolean;
  /** Medical equipment available */
  medical?: boolean;
  /** Flight attendant */
  flightAttendant?: boolean;
  /** Leather seats */
  leatherSeats?: boolean;
  /** Air conditioning */
  airConditioning?: boolean;
}

// =============================================================================
// SERVICE INPUT TYPES
// =============================================================================

/**
 * Input for creating a new contract record
 *
 * The contract_number is auto-generated by PostgreSQL's generate_contract_number()
 * function, so it should not be provided here.
 */
export interface CreateContractInput {
  /** UUID of the request this contract is for (required) */
  request_id: string;
  /** UUID of the ISO agent creating the contract (required) */
  iso_agent_id: string;
  /** UUID of the proposal this contract is based on (optional) */
  proposal_id?: string;
  /** UUID of the quote being contracted (optional) */
  quote_id?: string;
  /** UUID of the client profile (optional) */
  client_profile_id?: string;
  /** Reference to original quote number */
  reference_quote_number?: string;
  /** Customer information */
  customer: ContractCustomer;
  /** Flight details */
  flightDetails: ContractFlightDetails;
  /** Pricing breakdown */
  pricing: ContractPricing;
  /** Amenities */
  amenities?: ContractAmenities;
  /** Selected payment method */
  paymentMethod?: 'wire' | 'credit_card';
  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * File metadata for contract PDF storage
 */
export interface ContractFileMetadata {
  /** Original filename */
  file_name: string;
  /** Public URL to access the file */
  file_url: string;
  /** Storage bucket path */
  file_path: string;
  /** Size in bytes */
  file_size_bytes: number;
}

/**
 * Email metadata for tracking sent contracts
 */
export interface ContractEmailMetadata {
  /** Email address the contract was sent to */
  sent_to_email: string;
  /** Email message ID from Gmail */
  email_message_id?: string;
}

/**
 * Signature data for contract signing
 */
export interface ContractSignatureData {
  /** Signature image data (base64 or signature pad JSON) */
  signature_data: string;
  /** Name as signed */
  signed_name: string;
  /** Signature timestamp */
  signed_date: string;
}

/**
 * Payment data for contract payment tracking
 */
export interface ContractPaymentData {
  /** Payment reference (wire ref or CC transaction ID) */
  payment_reference: string;
  /** Amount paid */
  payment_amount: number;
  /** Payment date */
  payment_date: string;
  /** Last 4 digits of credit card (if applicable) */
  cc_last_four?: string;
  /** Payment method used */
  payment_method: 'wire' | 'credit_card' | 'check';
}

// =============================================================================
// SERVICE RESPONSE TYPES
// =============================================================================

/**
 * Result of creating a contract in the database
 */
export interface CreateContractResult {
  /** Database UUID of the contract */
  id: string;
  /** Auto-generated contract number (e.g., 'CONTRACT-2026-001') */
  contract_number: string;
  /** Current status */
  status: ContractStatus;
  /** Creation timestamp */
  created_at: string;
}

/**
 * Result of updating a contract's generated state
 */
export interface UpdateContractGeneratedResult {
  /** Database UUID */
  id: string;
  /** Contract number */
  contract_number: string;
  /** Updated status */
  status: ContractStatus;
  /** File URL */
  file_url: string | null;
  /** Generated timestamp */
  generated_at: string | null;
}

/**
 * Result of updating a contract's sent state
 */
export interface UpdateContractSentResult {
  /** Database UUID */
  id: string;
  /** Contract number */
  contract_number: string;
  /** Updated status (should be 'sent') */
  status: ContractStatus;
  /** Email recipient */
  sent_to_email: string | null;
  /** Sent timestamp */
  sent_at: string | null;
}

/**
 * Result of updating a contract's signed state
 */
export interface UpdateContractSignedResult {
  /** Database UUID */
  id: string;
  /** Contract number */
  contract_number: string;
  /** Updated status (should be 'signed') */
  status: ContractStatus;
  /** Client's signed name */
  client_signed_name: string | null;
  /** Signed timestamp */
  signed_at: string | null;
}

/**
 * Result of updating a contract's payment state
 */
export interface UpdateContractPaymentResult {
  /** Database UUID */
  id: string;
  /** Contract number */
  contract_number: string;
  /** Updated status (should be 'paid') */
  status: ContractStatus;
  /** Payment reference */
  payment_reference: string | null;
  /** Payment amount */
  payment_amount: number | null;
  /** Payment timestamp */
  payment_received_at: string | null;
}

// =============================================================================
// PDF GENERATION TYPES
// =============================================================================

/**
 * Input for generating a contract PDF
 */
export interface GenerateContractInput {
  /** Request UUID */
  requestId: string;
  /** ISO agent UUID */
  isoAgentId: string;
  /** Proposal UUID (optional) */
  proposalId?: string;
  /** Quote UUID (optional) */
  quoteId?: string;
  /** Client profile UUID (optional) */
  clientProfileId?: string;
  /** Reference quote number */
  referenceQuoteNumber?: string;
  /** Customer information */
  customer: ContractCustomer;
  /** Flight details */
  flightDetails: ContractFlightDetails;
  /** Pricing breakdown */
  pricing: ContractPricing;
  /** Amenities */
  amenities?: ContractAmenities;
  /** Payment method selection */
  paymentMethod?: 'wire' | 'credit_card';
  /** Save as draft in database */
  saveDraft?: boolean;
  /** Proposal PDF buffer to prepend as first pages of the contract */
  proposalPdfBuffer?: Buffer;
}

/**
 * Output from contract PDF generation
 */
export interface GenerateContractOutput {
  /** Generated contract ID (if saveDraft=true) */
  contractId?: string;
  /** Auto-generated contract number (if saveDraft=true) */
  contractNumber?: string;
  /** PDF as Buffer */
  pdfBuffer: Buffer;
  /** PDF as base64 string */
  pdfBase64: string;
  /** Generated filename */
  fileName: string;
  /** Generation timestamp */
  generatedAt: string;
  /** Pricing used in contract */
  pricing: ContractPricing;
}

// =============================================================================
// CONTRACT DATA FOR PDF TEMPLATE
// =============================================================================

/**
 * Complete contract data structure for PDF template rendering
 */
export interface ContractData {
  /** Contract ID (generated or from DB) */
  contractId: string;
  /** Contract number (e.g., "101225") */
  contractNumber: string;
  /** Generation timestamp */
  generatedAt: string;
  /** Customer information */
  customer: ContractCustomer;
  /** Flight details */
  flightDetails: ContractFlightDetails;
  /** Pricing breakdown */
  pricing: ContractPricing;
  /** Amenities list */
  amenities: ContractAmenities;
  /** Selected payment method */
  paymentMethod?: 'wire' | 'credit_card';
  /** Quote validity date */
  quoteValidUntil?: string;
}

// =============================================================================
// ITINERARY TYPES
// =============================================================================

/**
 * Itinerary leg for contract display
 * Matches the example contract itinerary table format
 */
export interface ContractItineraryLeg {
  /** Leg date (YYYY-MM-DD) */
  date: string;
  /** Estimated Time of Departure */
  etd: string;
  /** Estimated Time of Arrival */
  eta: string;
  /** Departure location (airport code + name) */
  departAirport: ContractAirport;
  /** Arrival location (airport code + name) */
  arriveAirport: ContractAirport;
  /** Number of passengers */
  pax: number;
  /** Estimated Time Enroute (duration) */
  ete: string;
  /** Distance in nautical miles */
  nm: number;
}

/**
 * Complete itinerary for multi-leg trips
 */
export interface ContractItinerary {
  /** All legs of the trip */
  legs: ContractItineraryLeg[];
  /** Whether times are local */
  localTimes: boolean;
}
