/**
 * Proposal Types
 *
 * TypeScript types for the proposal service layer.
 * Extends database types with service-specific interfaces.
 *
 * @see lib/services/proposal-service.ts
 * @see supabase/migrations/004_proposals_table.sql
 */

import type { Database } from './database';

// =============================================================================
// DATABASE TYPES (derived from Database schema)
// =============================================================================

/** Full proposal row from database */
export type Proposal = Database['public']['Tables']['proposals']['Row'];

/** Insert type for creating proposals */
export type ProposalInsert = Database['public']['Tables']['proposals']['Insert'];

/** Update type for modifying proposals */
export type ProposalUpdate = Database['public']['Tables']['proposals']['Update'];

/** Proposal status enum */
export type ProposalStatus = Database['public']['Enums']['proposal_status'];

// =============================================================================
// SERVICE INPUT TYPES
// =============================================================================

/**
 * Input for creating a new proposal record
 *
 * The proposal_number is auto-generated by PostgreSQL's generate_proposal_number()
 * function, so it should not be provided here.
 */
export interface CreateProposalInput {
  /** UUID of the request this proposal is for (required) */
  request_id: string;
  /** UUID of the ISO agent creating the proposal (required) */
  iso_agent_id: string;
  /** UUID of the quote this proposal is based on (optional) */
  quote_id?: string;
  /** UUID of the client profile (optional, can be auto-resolved from email) */
  client_profile_id?: string;
  /** Title of the proposal */
  title: string;
  /** Description/summary of the proposal */
  description?: string;
  /** Base total amount before margin */
  total_amount?: number;
  /** Margin/fee percentage applied (e.g., 10 for 10%) */
  margin_applied?: number;
  /** Final amount after margin */
  final_amount?: number;
  /** File name of the PDF */
  file_name: string;
  /** Public URL to access the PDF */
  file_url: string;
  /** Storage path of the PDF */
  file_path?: string;
  /** Size of the PDF in bytes */
  file_size_bytes?: number;
  /** Additional metadata as JSON */
  metadata?: Record<string, unknown>;
}

/**
 * File metadata returned from PDF upload
 */
export interface FileMetadata {
  /** Original filename */
  file_name: string;
  /** Public URL to access the file */
  file_url: string;
  /** Storage bucket path */
  file_path: string;
  /** Size in bytes */
  file_size_bytes: number;
}

/**
 * Email metadata for tracking sent proposals
 */
export interface EmailMetadata {
  /** Email address the proposal was sent to */
  sent_to_email: string;
  /** Name of the recipient */
  sent_to_name: string;
  /** Subject line of the email */
  email_subject: string;
  /** Body text of the email */
  email_body: string;
  /** Email message ID from the email service (optional) */
  email_message_id?: string;
}

/**
 * Pricing data for a proposal
 */
export interface ProposalPricing {
  /** Subtotal before fees */
  subtotal: number;
  /** Service fee amount */
  jetvisionFee: number;
  /** Taxes and other fees */
  taxes: number;
  /** Final total */
  total: number;
  /** Currency code (e.g., 'USD') */
  currency: string;
}

// =============================================================================
// SERVICE RESPONSE TYPES
// =============================================================================

/**
 * Result of creating a proposal in the database
 */
export interface CreateProposalResult {
  /** Database UUID of the proposal */
  id: string;
  /** Auto-generated proposal number (e.g., 'PROP-2025-001') */
  proposal_number: string;
  /** Current status */
  status: ProposalStatus;
  /** Creation timestamp */
  created_at: string;
}

/**
 * Result of updating a proposal's generated state
 */
export interface UpdateGeneratedResult {
  /** Database UUID */
  id: string;
  /** Proposal number */
  proposal_number: string;
  /** Updated status (should be 'generated') */
  status: ProposalStatus;
  /** File URL */
  file_url: string;
  /** Generated timestamp */
  generated_at: string | null;
}

/**
 * Result of updating a proposal's sent state
 */
export interface UpdateSentResult {
  /** Database UUID */
  id: string;
  /** Proposal number */
  proposal_number: string;
  /** Updated status (should be 'sent') */
  status: ProposalStatus;
  /** Email recipient */
  sent_to_email: string | null;
  /** Sent timestamp */
  sent_at: string | null;
}
