-- Migration: Add email approval fields to proposals table
-- Date: 2026-01-28
-- Description: Adds human-in-the-loop email approval workflow fields to the proposals table
--
-- Run this migration in Supabase SQL Editor or via CLI:
-- supabase db push

-- =============================================================================
-- STEP 1: Add email approval status tracking
-- =============================================================================

-- Add email approval status field
-- Values: 'not_required' | 'pending' | 'approved' | 'rejected' | 'needs_revision'
ALTER TABLE proposals
ADD COLUMN IF NOT EXISTS email_approval_status TEXT DEFAULT 'not_required'
  CHECK (email_approval_status IN ('not_required', 'pending', 'approved', 'rejected', 'needs_revision'));

COMMENT ON COLUMN proposals.email_approval_status IS 'Status of email approval workflow: not_required (no approval needed), pending (awaiting user approval), approved (user approved send), rejected (user rejected), needs_revision (user requested changes)';

-- =============================================================================
-- STEP 2: Add email draft fields
-- =============================================================================

-- Store the draft email subject
ALTER TABLE proposals
ADD COLUMN IF NOT EXISTS email_draft_subject TEXT;

COMMENT ON COLUMN proposals.email_draft_subject IS 'Draft email subject for approval workflow';

-- Store the draft email body (HTML)
ALTER TABLE proposals
ADD COLUMN IF NOT EXISTS email_draft_body TEXT;

COMMENT ON COLUMN proposals.email_draft_body IS 'Draft email body (HTML) for approval workflow';

-- Track when the email draft was generated
ALTER TABLE proposals
ADD COLUMN IF NOT EXISTS email_draft_generated_at TIMESTAMPTZ;

COMMENT ON COLUMN proposals.email_draft_generated_at IS 'When the email draft was generated by the agent';

-- =============================================================================
-- STEP 3: Add email approval tracking fields
-- =============================================================================

-- Track when the email was approved
ALTER TABLE proposals
ADD COLUMN IF NOT EXISTS email_approved_at TIMESTAMPTZ;

COMMENT ON COLUMN proposals.email_approved_at IS 'When the user approved sending the email';

-- Store any notes from the approval process (e.g., reason for rejection)
ALTER TABLE proposals
ADD COLUMN IF NOT EXISTS email_approval_notes TEXT;

COMMENT ON COLUMN proposals.email_approval_notes IS 'Notes from the approval process (e.g., rejection reason)';

-- =============================================================================
-- STEP 4: Add index for querying pending approvals
-- =============================================================================

-- Create index for efficiently querying proposals pending email approval
CREATE INDEX IF NOT EXISTS idx_proposals_email_approval_pending
ON proposals (iso_agent_id, email_approval_status)
WHERE email_approval_status = 'pending';

COMMENT ON INDEX idx_proposals_email_approval_pending IS 'Efficient lookup of proposals pending email approval by ISO agent';

-- =============================================================================
-- STEP 5: Update messages content_type enum to support new types
-- =============================================================================

-- Note: The messages.content_type column uses a PostgreSQL ENUM type (message_content_type).
-- We need to add new values to the enum type.
-- Using 'IF NOT EXISTS' syntax (PostgreSQL 9.3+) to make migration idempotent.

-- Add new enum values for email approval workflow
ALTER TYPE message_content_type ADD VALUE IF NOT EXISTS 'email_approval_request';
ALTER TYPE message_content_type ADD VALUE IF NOT EXISTS 'email_approved';
ALTER TYPE message_content_type ADD VALUE IF NOT EXISTS 'email_rejected';

-- Also add 'contract_shared' if it doesn't exist (from contracts feature)
ALTER TYPE message_content_type ADD VALUE IF NOT EXISTS 'contract_shared';

-- =============================================================================
-- VERIFICATION
-- =============================================================================

-- Verify columns were added successfully
DO $$
DECLARE
  col_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO col_count
  FROM information_schema.columns
  WHERE table_name = 'proposals'
    AND column_name IN (
      'email_approval_status',
      'email_draft_subject',
      'email_draft_body',
      'email_draft_generated_at',
      'email_approved_at',
      'email_approval_notes'
    );

  IF col_count < 6 THEN
    RAISE EXCEPTION 'Migration incomplete: Expected 6 new columns, found %', col_count;
  END IF;

  RAISE NOTICE 'Migration complete: Added % email approval columns to proposals table', col_count;
END $$;
