name: Auto Create PR for Feature Branches

on:
  push:
    branches:
      - 'feat/**'
      - 'feature/**'
      - 'fix/**'

permissions:
  pull-requests: write
  contents: read

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract branch info
        id: branch_info
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

          # Extract issue number if present (e.g., ONEK-71 from feat/ONEK-71-mock-data)
          ISSUE_NUM=$(echo "$BRANCH_NAME" | grep -oP '(ONEK|DES)-\d+' | head -1 || echo "")
          echo "issue_num=$ISSUE_NUM" >> $GITHUB_OUTPUT

      - name: Check if PR already exists
        id: check_pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_EXISTS=$(gh pr list --head "${{ steps.branch_info.outputs.branch_name }}" --json number --jq length)
          echo "pr_exists=$PR_EXISTS" >> $GITHUB_OUTPUT

      - name: Generate PR title and body
        id: pr_content
        if: steps.check_pr.outputs.pr_exists == '0'
        run: |
          BRANCH_NAME="${{ steps.branch_info.outputs.branch_name }}"
          ISSUE_NUM="${{ steps.branch_info.outputs.issue_num }}"

          # Extract commit messages for PR body
          COMMITS=$(git log --oneline origin/main..HEAD | sed 's/^/- /')

          # Generate title
          if [ -n "$ISSUE_NUM" ]; then
            TITLE="feat($ISSUE_NUM): ${BRANCH_NAME#*-}"
          else
            TITLE="${BRANCH_NAME}"
          fi

          # Generate body
          cat > /tmp/pr_body.md << EOF
          ## Summary

          Auto-generated PR for branch: \`$BRANCH_NAME\`

          ## Commits

          $COMMITS

          ## Linear Issue

          ${ISSUE_NUM:+- **$ISSUE_NUM**: https://linear.app/designthru-ai/issue/$ISSUE_NUM}

          ## Checklist

          - [ ] Tests pass locally
          - [ ] Code follows project style guidelines
          - [ ] Documentation updated
          - [ ] Linear issue updated

          🤖 Auto-generated by GitHub Actions

          Co-Authored-By: Claude <noreply@anthropic.com>
          EOF

          echo "title=$TITLE" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.check_pr.outputs.pr_exists == '0'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --title "${{ steps.pr_content.outputs.title }}" \
            --body-file /tmp/pr_body.md \
            --base main \
            --head "${{ steps.branch_info.outputs.branch_name }}"

      - name: PR already exists
        if: steps.check_pr.outputs.pr_exists != '0'
        run: |
          echo "PR already exists for branch ${{ steps.branch_info.outputs.branch_name }}"
          gh pr list --head "${{ steps.branch_info.outputs.branch_name }}"
        env:
          GH_TOKEN: ${{ github.token }}
